export const CREATE_DISCUSSION = 'CREATE_DISCUSSION';
export const UPDATE_DISCUSSION = 'UPDATE_DISCUSSION';
export const DELETE_DISCUSSION = 'DELETE_DISCUSSION';
export const FETCH_DISCUSSIONS = 'FETCH_DISCUSSIONS';